language: python

env:
  - TOXENV=py27-1.6
  - TOXENV=py27-1.7
  - TOXENV=py33-1.6
  - TOXENV=py33-1.7
  - TOXENV=py34-1.6
  - TOXENV=py34-1.7

install:
  - pip install tox coveralls

script:
  - tox

after_success: coveralls